export interface QuizImage {
  id: number;
  uri: string;
  name: string;
  colors: string[];
  scene: 'indoor' | 'outdoor';
  sentiment: 'happy' | 'sad' | 'neutral' | 'angry';
  count: number;
  orientation: 'portrait' | 'landscape';
  category: 'animal' | 'fruit' | 'animated_celebrity' | 'body_part' | 'stadium' | 'object';
  tags: string[];
}

export const IMAGES: QuizImage[] = [
  // === ANIMALS (1-20) ===
  {
    id: 1,
    uri: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?q=80&w=600",
    name: "Cat",
    colors: ["orange", "white", "grey"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["cat", "pet", "feline", "furry", "cute", "domestic"]
  },
  {
    id: 2,
    uri: "https://images.unsplash.com/photo-1543466835-00a7907e9de1?q=80&w=600",
    name: "Dog",
    colors: ["brown", "white"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["dog", "pet", "canine", "happy", "mammal", "outdoor"]
  },
  {
    id: 3,
    uri: "https://images.unsplash.com/photo-1552053831-71594a27632d?q=80&w=600",
    name: "Golden Retriever",
    colors: ["yellow", "gold"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animal",
    tags: ["dog", "retriever", "golden", "happy", "pet", "canine"]
  },
  {
    id: 4,
    uri: "https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?q=80&w=600",
    name: "Rabbit",
    colors: ["white", "pink"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["rabbit", "bunny", "hare", "cute", "grass", "mammal"]
  },
  {
    id: 5,
    uri: "https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?q=80&w=600",
    name: "Parrot",
    colors: ["green", "red", "blue"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animal",
    tags: ["parrot", "bird", "exotic", "feather", "colorful", "tropical"]
  },
  {
    id: 6,
    uri: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?q=80&w=600",
    name: "Fox",
    colors: ["orange", "brown", "white"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["fox", "wildlife", "orange", "mammal", "nature", "predator"]
  },
  {
    id: 7,
    uri: "https://images.unsplash.com/photo-1533738363-b7f9aef128ce?q=80&w=600",
    name: "Kitten with Glasses",
    colors: ["grey", "white", "black"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animal",
    tags: ["cat", "kitten", "glasses", "cute", "funny", "pet"]
  },
  {
    id: 8,
    uri: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?q=80&w=600",
    name: "Lion",
    colors: ["yellow", "brown"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["lion", "predator", "feline", "wildlife", "safari", "king"]
  },
  {
    id: 9,
    uri: "https://images.unsplash.com/photo-1484406566174-9da000fda645?q=80&w=600",
    name: "Deer",
    colors: ["brown", "white"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["deer", "forest", "wildlife", "mammal", "nature", "buck"]
  },
  {
    id: 10,
    uri: "https://images.unsplash.com/photo-1522069169874-c58ec4b76be5?q=80&w=600",
    name: "Goldfish",
    colors: ["orange", "yellow", "blue"],
    scene: "indoor",
    sentiment: "neutral",
    count: 3,
    orientation: "landscape",
    category: "animal",
    tags: ["fish", "goldfish", "aquarium", "water", "pet", "swimming"]
  },
  {
    id: 11,
    uri: "https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?q=80&w=600",
    name: "Panda",
    colors: ["black", "white", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animal",
    tags: ["panda", "bear", "bamboo", "china", "wildlife", "mammal"]
  },
  {
    id: 12,
    uri: "https://images.unsplash.com/photo-1571741001402-fc8e12d8a1ee?q=80&w=600",
    name: "Koala",
    colors: ["grey", "green"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "animal",
    tags: ["koala", "australia", "eucalyptus", "marsupial", "cute", "mammal"]
  },
  {
    id: 13,
    uri: "https://images.unsplash.com/photo-1535268647977-a403b69fc756?q=80&w=600",
    name: "Sea Turtle",
    colors: ["green", "blue", "brown"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["turtle", "ocean", "marine", "swimming", "reptile,nature"]
  },
  {
    id: 14,
    uri: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?q=80&w=600",
    name: "Elephant",
    colors: ["grey", "green", "blue"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["elephant", "mammal", "safari", "trunk", "wildlife,nature"]
  },
  {
    id: 15,
    uri: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?q=80&w=600",
    name: "Leopard",
    colors: ["yellow", "black", "spots"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["leopard", "feline", "spots", "predator", "safari", "wildlife"]
  },
  {
    id: 16,
    uri: "https://images.unsplash.com/photo-1557008075-7f2c5efa4cfd?q=80&w=600",
    name: "Red Panda",
    colors: ["orange", "white", "black"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["panda", "red", "bamboo", "cute", "mammal", "furry"]
  },
  {
    id: 17,
    uri: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?q=80&w=600",
    name: "Butterfly",
    colors: ["blue", "black", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["butterfly", "insect", "wings", "flower", "garden,nature"]
  },
  {
    id: 18,
    uri: "https://images.unsplash.com/photo-1512446813927-4a7878eb4ab6?q=80&w=600",
    name: "Cute Hamster",
    colors: ["white", "brown"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animal",
    tags: ["hamster", "rodent", "pet", "cute", "furry,small"]
  },
  {
    id: 19,
    uri: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?q=80&w=600",
    name: "Sleek Black Cat",
    colors: ["black", "green"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animal",
    tags: ["cat", "black", "pet", "feline", "sleek,domestic"]
  },
  {
    id: 20,
    uri: "https://images.unsplash.com/photo-1534361960057-19889db9621e?q=80&w=600",
    name: "Puppies playing",
    colors: ["yellow", "brown", "white"],
    scene: "outdoor",
    sentiment: "happy",
    count: 3,
    orientation: "landscape",
    category: "animal",
    tags: ["dog", "puppy", "playing", "happy", "pet", "canine"]
  },

  // === FRUITS (21-40) ===
  {
    id: 21,
    uri: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?q=80&w=600",
    name: "Red Apple",
    colors: ["red", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "fruit",
    tags: ["apple", "fruit", "red", "sweet", "crisp,healthy"]
  },
  {
    id: 22,
    uri: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=600",
    name: "Bananas",
    colors: ["yellow", "green"],
    scene: "indoor",
    sentiment: "neutral",
    count: 5,
    orientation: "landscape",
    category: "fruit",
    tags: ["banana", "fruit", "yellow", "bunch", "sweet,tropical"]
  },
  {
    id: 23,
    uri: "https://images.unsplash.com/photo-1547514701-42782101795e?q=80&w=600",
    name: "Oranges",
    colors: ["orange", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 3,
    orientation: "landscape",
    category: "fruit",
    tags: ["orange", "citrus", "fruit", "sweet", "juicy,healthy"]
  },
  {
    id: 24,
    uri: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=600",
    name: "Strawberries",
    colors: ["red", "green"],
    scene: "indoor",
    sentiment: "happy",
    count: 10,
    orientation: "landscape",
    category: "fruit",
    tags: ["strawberry", "berry", "red", "sweet", "fruit,summer"]
  },
  {
    id: 25,
    uri: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?q=80&w=600",
    name: "Grapes",
    colors: ["purple", "green"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 30,
    orientation: "portrait",
    category: "fruit",
    tags: ["grape", "vineyard", "fruit", "purple", "sweet,healthy"]
  },
  {
    id: 26,
    uri: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=600",
    name: "Watermelon Slice",
    colors: ["red", "green", "black"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "fruit",
    tags: ["watermelon", "summer", "refreshing", "fruit", "slice,sweet"]
  },
  {
    id: 27,
    uri: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?q=80&w=600",
    name: "Pineapple",
    colors: ["gold", "brown", "green"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "fruit",
    tags: ["pineapple", "tropical", "fruit", "sweet", "spiky,gold"]
  },
  {
    id: 28,
    uri: "https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=600",
    name: "Mangoes",
    colors: ["orange", "yellow", "red"],
    scene: "indoor",
    sentiment: "neutral",
    count: 2,
    orientation: "landscape",
    category: "fruit",
    tags: ["mango", "tropical", "fruit", "sweet", "juicy,peach"]
  },
  {
    id: 29,
    uri: "https://images.unsplash.com/photo-1528825871115-3581a5387919?q=80&w=600",
    name: "Peaches",
    colors: ["pink", "orange", "yellow"],
    scene: "outdoor",
    sentiment: "happy",
    count: 4,
    orientation: "landscape",
    category: "fruit",
    tags: ["peach", "fruit", "sweet", "fuzzy", "summer,juicy"]
  },
  {
    id: 30,
    uri: "https://images.unsplash.com/photo-1527661591475-527312dd65f5?q=80&w=600",
    name: "Cherries",
    colors: ["red", "dark"],
    scene: "indoor",
    sentiment: "happy",
    count: 15,
    orientation: "landscape",
    category: "fruit",
    tags: ["cherry", "fruit", "red", "sweet", "stem,berries"]
  },
  {
    id: 31,
    uri: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?q=80&w=600",
    name: "Blueberries",
    colors: ["blue", "dark"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 50,
    orientation: "landscape",
    category: "fruit",
    tags: ["blueberry", "berry", "blue", "sweet", "fruit", "superfood"]
  },
  {
    id: 32,
    uri: "https://images.unsplash.com/photo-1585059895524-72359e061381?q=80&w=600",
    name: "Kiwis",
    colors: ["brown", "green"],
    scene: "indoor",
    sentiment: "neutral",
    count: 3,
    orientation: "portrait",
    category: "fruit",
    tags: ["kiwi", "fruit", "green", "sliced", "fuzzy", "tart"]
  },
  {
    id: 33,
    uri: "https://images.unsplash.com/photo-1590502593747-42a996133562?q=80&w=600",
    name: "Lemons",
    colors: ["yellow"],
    scene: "indoor",
    sentiment: "happy",
    count: 6,
    orientation: "landscape",
    category: "fruit",
    tags: ["lemon", "citrus", "yellow", "sour,acidic,fruit"]
  },
  {
    id: 34,
    uri: "https://images.unsplash.com/photo-1591013759972-ee1e689848a8?q=80&w=600",
    name: "Limes",
    colors: ["green"],
    scene: "indoor",
    sentiment: "neutral",
    count: 5,
    orientation: "landscape",
    category: "fruit",
    tags: ["lime", "citrus", "green", "sour,tart,cocktail"]
  },
  {
    id: 35,
    uri: "https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?q=80&w=600",
    name: "Pears",
    colors: ["green", "yellow", "brown"],
    scene: "indoor",
    sentiment: "neutral",
    count: 3,
    orientation: "landscape",
    category: "fruit",
    tags: ["pear", "fruit", "sweet", "green", "healthy,orchard"]
  },
  {
    id: 36,
    uri: "https://images.unsplash.com/photo-1603052875302-d376b7c0638a?q=80&w=600",
    name: "Plums",
    colors: ["purple", "dark", "red"],
    scene: "outdoor",
    sentiment: "happy",
    count: 4,
    orientation: "portrait",
    category: "fruit",
    tags: ["plum", "fruit", "purple", "sweet", "juicy,stonefruit"]
  },
  {
    id: 37,
    uri: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?q=80&w=600",
    name: "Avocado",
    colors: ["green", "brown", "black"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "fruit",
    tags: ["avocado", "fruit", "green", "healthy", "guacamole,toast"]
  },
  {
    id: 38,
    uri: "https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?q=80&w=600",
    name: "Pomegranates",
    colors: ["red", "pink"],
    scene: "indoor",
    sentiment: "neutral",
    count: 2,
    orientation: "landscape",
    category: "fruit",
    tags: ["pomegranate", "fruit", "red", "seeds,healthy,sweet"]
  },
  {
    id: 39,
    uri: "https://images.unsplash.com/photo-1584306380961-336d3969a4e3?q=80&w=600",
    name: "Coconuts",
    colors: ["brown", "white"],
    scene: "outdoor",
    sentiment: "happy",
    count: 2,
    orientation: "portrait",
    category: "fruit",
    tags: ["coconut", "tropical", "fruit", "brown", "husk,water"]
  },
  {
    id: 40,
    uri: "https://images.unsplash.com/photo-1526318896980-cf78c088247c?q=80&w=600",
    name: "Papaya",
    colors: ["orange", "green", "black"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "fruit",
    tags: ["papaya", "tropical", "fruit", "orange", "sweet,seeds"]
  },

  // === ANIMATED CELEBRITIES (41-60) ===
  {
    id: 41,
    uri: "https://images.unsplash.com/photo-1608889174637-3c44f6326f1a?q=80&w=600",
    name: "Toy Cowboy (Woody)",
    colors: ["yellow", "blue", "brown"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animated_celebrity",
    tags: ["toy", "woody", "cowboy", "sheriff", "pixar,disney"]
  },
  {
    id: 42,
    uri: "https://images.unsplash.com/photo-1608889175123-8ec330b86f84?q=80&w=600",
    name: "Space Ranger (Buzz)",
    colors: ["white", "green", "purple"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animated_celebrity",
    tags: ["buzz", "lightyear", "space", "ranger", "pixar,disney"]
  },
  {
    id: 43,
    uri: "https://images.unsplash.com/photo-1601856389534-916c4c122b44?q=80&w=600",
    name: "Anime Ninja (Naruto)",
    colors: ["orange", "black", "yellow"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["naruto", "ninja", "anime", "manga", "japan,leaf"]
  },
  {
    id: 44,
    uri: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600",
    name: "Anime Saiyan (Goku)",
    colors: ["orange", "blue", "black"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["goku", "dbz", "anime", "manga", "saiyan,super"]
  },
  {
    id: 45,
    uri: "https://images.unsplash.com/photo-1618336753974-aae8e04506aa?q=80&w=600",
    name: "Pocket Monster (Pikachu)",
    colors: ["yellow", "red", "black"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animated_celebrity",
    tags: ["pikachu", "pokemon", "yellow", "anime", "nintendo,game"]
  },
  {
    id: 46,
    uri: "https://images.unsplash.com/photo-1559863040-3a2a5c4257c9?q=80&w=600",
    name: "SpongeBob SquarePants",
    colors: ["yellow", "brown", "white"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animated_celebrity",
    tags: ["spongebob", "sponge", "squarepants", "yellow", "cartoon,nickelodeon"]
  },
  {
    id: 47,
    uri: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?q=80&w=600",
    name: "Mickey Mouse Statue",
    colors: ["black", "red", "yellow"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["mickey", "mouse", "disney", "cartoon", "retro,statue"]
  },
  {
    id: 48,
    uri: "https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?q=80&w=600",
    name: "Pink Blob (Kirby)",
    colors: ["pink", "red", "blue"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["kirby", "pink", "nintendo", "game", "cute", "cartoon"]
  },
  {
    id: 49,
    uri: "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=600",
    name: "Green Ogre (Shrek)",
    colors: ["green", "brown"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["shrek", "ogre", "green", "swamp", "dreamworks,fairy"]
  },
  {
    id: 50,
    uri: "https://images.unsplash.com/photo-1614036417651-efe5912149d8?q=80&w=600",
    name: "Yellow Minion",
    colors: ["yellow", "blue"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["minion", "yellow", "goggles", "despicable", "gru,cartoon"]
  },
  {
    id: 51,
    uri: "https://images.unsplash.com/photo-1622737133809-d95047b9e673?q=80&w=600",
    name: "Spider-Man Figure",
    colors: ["red", "blue", "black"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["spiderman", "hero", "marvel", "comics", "red", "web"]
  },
  {
    id: 52,
    uri: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=600",
    name: "Batman Figurine",
    colors: ["black", "grey", "gold"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["batman", "dark", "knight", "hero", "dc", "comics"]
  },
  {
    id: 53,
    uri: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600",
    name: "Gaming Plumber (Mario)",
    colors: ["red", "blue", "white"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animated_celebrity",
    tags: ["mario", "nintendo", "plumber", "red", "game", "bros"]
  },
  {
    id: 54,
    uri: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=600",
    name: "Totoro Statue",
    colors: ["grey", "white", "green"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "animated_celebrity",
    tags: ["totoro", "ghibli", "anime", "japan", "forest,cute"]
  },
  {
    id: 55,
    uri: "https://images.unsplash.com/photo-1593085512500-5d55148d6f0d?q=80&w=600",
    name: "Yellow Duck (Donald)",
    colors: ["white", "blue", "yellow"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["donald", "duck", "disney", "sailor", "cartoon,vintage"]
  },
  {
    id: 56,
    uri: "https://images.unsplash.com/photo-1531259683007-016a7b628fc3?q=80&w=600",
    name: "Homer Simpson Pop",
    colors: ["yellow", "white", "blue"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["homer", "simpson", "yellow", "donut", "springfield", "cartoon"]
  },
  {
    id: 57,
    uri: "https://images.unsplash.com/photo-1608889168494-df9b4395e263?q=80&w=600",
    name: "Garfield Toy",
    colors: ["orange", "black"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["garfield", "cat", "orange", "lasagna", "monday", "cartoon"]
  },
  {
    id: 58,
    uri: "https://images.unsplash.com/photo-1580234810907-b40315b76418?q=80&w=600",
    name: "Sailor Moon Action Fig",
    colors: ["blue", "white", "yellow"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "animated_celebrity",
    tags: ["sailor", "moon", "anime", "manga", "japan,heroine"]
  },
  {
    id: 59,
    uri: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=600",
    name: "Aladdin Genie Art",
    colors: ["blue", "gold"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["genie", "aladdin", "blue", "magic", "lamp", "disney"]
  },
  {
    id: 60,
    uri: "https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?q=80&w=600",
    name: "Winnie the Pooh Plush",
    colors: ["yellow", "red"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "animated_celebrity",
    tags: ["pooh", "bear", "winnie", "honey", "disney", "yellow"]
  },

  // === BODY PARTS (61-80) ===
  {
    id: 61,
    uri: "https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=600",
    name: "Human Brain Model",
    colors: ["pink", "grey", "white"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "body_part",
    tags: ["brain", "organ", "anatomy", "intelligence", "mind", "head"]
  },
  {
    id: 62,
    uri: "https://images.unsplash.com/photo-1576086213369-97a306d36557?q=80&w=600",
    name: "Human Heart Art",
    colors: ["red", "blue"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["heart", "organ", "anatomy", "cardio", "chest", "blood"]
  },
  {
    id: 63,
    uri: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600",
    name: "Human Eye",
    colors: ["blue", "black", "white"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["eye", "sight", "vision", "pupil", "iris", "face"]
  },
  {
    id: 64,
    uri: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?q=80&w=600",
    name: "Holding Hands",
    colors: ["skin", "brown"],
    scene: "outdoor",
    sentiment: "happy",
    count: 2,
    orientation: "landscape",
    category: "body_part",
    tags: ["hand", "fingers", "holding", "skin", "touch", "arm"]
  },
  {
    id: 65,
    uri: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600",
    name: "Ear Close Up",
    colors: ["skin", "gold"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["ear", "hearing", "listen", "audio", "skin", "head"]
  },
  {
    id: 66,
    uri: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600",
    name: "Human Nose",
    colors: ["skin", "pink"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["nose", "smell", "scent", "breathing", "skin", "face"]
  },
  {
    id: 67,
    uri: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600",
    name: "White Teeth",
    colors: ["white", "pink"],
    scene: "indoor",
    sentiment: "happy",
    count: 32,
    orientation: "portrait",
    category: "body_part",
    tags: ["tooth", "teeth", "smile", "dentist", "mouth", "white"]
  },
  {
    id: 68,
    uri: "https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=600",
    name: "Lungs Diagram",
    colors: ["pink", "red"],
    scene: "indoor",
    sentiment: "neutral",
    count: 2,
    orientation: "landscape",
    category: "body_part",
    tags: ["lung", "lungs", "breathing", "oxygen", "organ", "chest"]
  },
  {
    id: 69,
    uri: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=600",
    name: "Human Skull Model",
    colors: ["white", "grey"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["skull", "bone", "skeleton", "head", "anatomy", "death"]
  },
  {
    id: 70,
    uri: "https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=600",
    name: "Bones Skeleton",
    colors: ["white", "grey"],
    scene: "indoor",
    sentiment: "neutral",
    count: 206,
    orientation: "landscape",
    category: "body_part",
    tags: ["bone", "skeleton", "anatomy", "ribs", "spine", "joint"]
  },
  {
    id: 71,
    uri: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600",
    name: "Muscles Arm",
    colors: ["skin", "brown"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["bicep", "muscle", "arm", "strength", "fitness", "workout"]
  },
  {
    id: 72,
    uri: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=600",
    name: "Runner Legs",
    colors: ["skin", "black"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 2,
    orientation: "portrait",
    category: "body_part",
    tags: ["leg", "legs", "running", "feet", "muscles", "fitness"]
  },
  {
    id: 73,
    uri: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600",
    name: "Human Tongue",
    colors: ["pink", "red"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["tongue", "mouth", "taste", "speak", "pink", "saliva"]
  },
  {
    id: 74,
    uri: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600",
    name: "Fingers Close Up",
    colors: ["skin", "white"],
    scene: "indoor",
    sentiment: "neutral",
    count: 5,
    orientation: "portrait",
    category: "body_part",
    tags: ["finger", "fingers", "hand", "nail", "touch", "skin"]
  },
  {
    id: 75,
    uri: "https://images.unsplash.com/photo-1559757175-5700dde675bc?q=80&w=600",
    name: "Kidney Model",
    colors: ["red", "brown"],
    scene: "indoor",
    sentiment: "neutral",
    count: 2,
    orientation: "landscape",
    category: "body_part",
    tags: ["kidney", "organ", "urology", "anatomy", "filtration", "abdomen"]
  },
  {
    id: 76,
    uri: "https://images.unsplash.com/photo-1512152272829-e3139592d56f?q=80&w=600",
    name: "Rib Cage Model",
    colors: ["white", "grey"],
    scene: "indoor",
    sentiment: "neutral",
    count: 24,
    orientation: "landscape",
    category: "body_part",
    tags: ["ribs", "chest", "cage", "bone", "skeleton", "protection"]
  },
  {
    id: 77,
    uri: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=600",
    name: "Curly Hair",
    colors: ["brown", "black"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["hair", "curls", "head", "brunette", "style", "scalp"]
  },
  {
    id: 78,
    uri: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=600",
    name: "Human Face",
    colors: ["skin", "pink"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["face", "eyes", "nose", "mouth", "features", "portrait"]
  },
  {
    id: 79,
    uri: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600",
    name: "Human Chin/Jaw",
    colors: ["skin", "brown"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "body_part",
    tags: ["jaw", "chin", "beard", "face", "anatomy", "profile"]
  },
  {
    id: 80,
    uri: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?q=80&w=600",
    name: "Fists Clashed",
    colors: ["skin", "brown"],
    scene: "outdoor",
    sentiment: "happy",
    count: 2,
    orientation: "landscape",
    category: "body_part",
    tags: ["fist", "hand", "punch", "clashed", "knuckles", "strength"]
  },

  // === STADIUMS (81-100) ===
  {
    id: 81,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Soccer Stadium",
    colors: ["green", "blue", "white"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["stadium", "soccer", "arena", "field", "grass", "match"]
  },
  {
    id: 82,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Baseball Stadium",
    colors: ["green", "brown", "blue"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["baseball", "stadium", "field", "diamond", "stands", "game"]
  },
  {
    id: 83,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Wembley Stadium",
    colors: ["green", "silver", "blue"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["wembley", "stadium", "london", "soccer", "arena", "arch"]
  },
  {
    id: 84,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Camp Nou",
    colors: ["blue", "red", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["barcelona", "stadium", "soccer", "campnou", "catalonia", "football"]
  },
  {
    id: 85,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Maracana Arena",
    colors: ["green", "yellow", "blue"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["rio", "brazil", "maracana", "soccer", "stadium", "football"]
  },
  {
    id: 86,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Allianz Arena",
    colors: ["white", "red", "blue"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["munich", "allianz", "germany", "stadium", "illuminated", "soccer"]
  },
  {
    id: 87,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Santiago Bernabeu",
    colors: ["grey", "blue", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["madrid", "real", "bernabeu", "soccer", "football", "stadium"]
  },
  {
    id: 88,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "San Siro",
    colors: ["grey", "red", "green"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["milan", "sansiro", "italy", "stadium", "soccer", "football"]
  },
  {
    id: 90,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Old Trafford",
    colors: ["red", "white", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["manchester", "oldtrafford,united", "stadium", "soccer", "football"]
  },
  {
    id: 90,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Anfield Ground",
    colors: ["red", "green", "blue"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["liverpool", "anfield", "stadium", "football", "soccer", "kop"]
  },
  {
    id: 91,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Rose Bowl",
    colors: ["green", "blue", "rose"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["rosebowl", "stadium", "pasadena", "california", "football", "stadium"]
  },
  {
    id: 92,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Tokyo Dome",
    colors: ["white", "grey", "blue"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["tokyo", "dome", "japan", "stadium", "baseball", "arena"]
  },
  {
    id: 93,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Cricket Ground",
    colors: ["green", "brown", "blue"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["cricket", "melbourne", "ground", "field", "wickets", "stadium"]
  },
  {
    id: 94,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Bird's Nest Beijing",
    colors: ["grey", "silver", "blue"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["beijing", "stadium", "olympic", "national", "china", "nest"]
  },
  {
    id: 95,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Azteca Stadium",
    colors: ["grey", "green", "yellow"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["azteca", "mexico", "soccer", "stadium", "football", "colossus"]
  },
  {
    id: 96,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Signal Iduna Park",
    colors: ["yellow", "black", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["dortmund", "westfalenstadion", "germany", "stadium", "yellow", "soccer"]
  },
  {
    id: 97,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Emirates Stadium",
    colors: ["red", "white", "grey"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["arsenal", "emirates", "london", "stadium", "soccer", "football"]
  },
  {
    id: 98,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Stamford Bridge",
    colors: ["blue", "white", "green"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["chelsea", "stamford", "london", "soccer", "stadium", "football"]
  },
  {
    id: 99,
    uri: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600",
    name: "Stade de France",
    colors: ["blue", "white", "red"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["paris", "stadium", "france", "national", "soccer", "football"]
  },
  {
    id: 100,
    uri: "https://images.unsplash.com/photo-1478147427282-58a87a120781?q=80&w=600",
    name: "Madison Square Garden",
    colors: ["grey", "blue", "gold"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "stadium",
    tags: ["madison", "square", "garden", "ny", "msg", "basketball", "arena"]
  },

  // === OBJECTS (101-120) ===
  {
    id: 101,
    uri: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=600",
    name: "Smart Phone",
    colors: ["pink", "gold", "white"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "object",
    tags: ["phone", "mobile", "smartphone", "device", "screen", "apple"]
  },
  {
    id: 102,
    uri: "https://images.unsplash.com/photo-1496181130204-755241544e35?q=80&w=600",
    name: "Laptop on Desk",
    colors: ["grey", "white", "brown"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["laptop", "computer", "desk", "work", "office", "screen"]
  },
  {
    id: 103,
    uri: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600",
    name: "Headphones",
    colors: ["black", "gold", "yellow"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["headphones", "music", "audio", "sound", "device", "listening"]
  },
  {
    id: 104,
    uri: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=600",
    name: "Sleek Wrist Watch",
    colors: ["silver", "white", "brown"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "object",
    tags: ["watch", "time", "wrist", "clock", "accessory", "silver"]
  },
  {
    id: 105,
    uri: "https://images.unsplash.com/photo-1481349518771-20055b2a7b24?q=80&w=600",
    name: "Fresh Banana",
    colors: ["yellow", "blue"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["banana", "fruit", "yellow", "peeled", "healthy", "sweet"]
  },
  {
    id: 106,
    uri: "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?q=80&w=600",
    name: "Retro Red Car",
    colors: ["red", "white", "black"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["car", "vehicle", "retro", "red", "automobile", "transport"]
  },
  {
    id: 107,
    uri: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=600",
    name: "Mountain Bicycle",
    colors: ["black", "blue", "green"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["bike", "bicycle", "mountain", "wheels", "sports", "cycle"]
  },
  {
    id: 108,
    uri: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=600",
    name: "Acoustic Guitar",
    colors: ["brown", "yellow", "black"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "object",
    tags: ["guitar", "music", "instrument", "acoustic", "strings", "wood"]
  },
  {
    id: 109,
    uri: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?q=80&w=600",
    name: "Sleek Modern Desk",
    colors: ["white", "grey"],
    scene: "indoor",
    sentiment: "neutral",
    count: 10,
    orientation: "landscape",
    category: "object",
    tags: ["desk", "table", "workplace", "office", "modern", "furniture"]
  },
  {
    id: 110,
    uri: "https://images.unsplash.com/photo-1512190987745-f282412b553a?q=80&w=600",
    name: "Leather Backpack",
    colors: ["brown", "gold"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "object",
    tags: ["backpack", "bag", "leather", "travel", "school", "accessory"]
  },
  {
    id: 111,
    uri: "https://images.unsplash.com/photo-1495107334309-fcf20504a5ab?q=80&w=600",
    name: "Polaroid Camera",
    colors: ["black", "grey", "red"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["camera", "polaroid", "photo", "retro", "vintage", "instant"]
  },
  {
    id: 112,
    uri: "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=600",
    name: "Vintage Typewriter",
    colors: ["black", "white", "grey"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["typewriter", "retro", "vintage", "writing", "antique", "keyboard"]
  },
  {
    id: 113,
    uri: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=600",
    name: "Sleek Sports Car",
    colors: ["yellow", "black"],
    scene: "outdoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["car", "sports", "yellow", "luxury", "fast,automobile"]
  },
  {
    id: 114,
    uri: "https://images.unsplash.com/photo-1534067783941-51c9c23eccfd?q=80&w=600",
    name: "Coffee Mug",
    colors: ["white", "brown", "grey"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "portrait",
    category: "object",
    tags: ["mug", "coffee", "tea", "ceramic", "cup", "drink"]
  },
  {
    id: 115,
    uri: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=600",
    name: "Succulent Plant",
    colors: ["green", "grey", "white"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "object",
    tags: ["plant", "succulent", "pot", "green", "indoor", "garden"]
  },
  {
    id: 116,
    uri: "https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?q=80&w=600",
    name: "Writing Notebook",
    colors: ["brown", "grey"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["notebook", "diary", "writing", "journal", "paper", "book"]
  },
  {
    id: 117,
    uri: "https://images.unsplash.com/photo-1532634922-8fe0b757fb13?q=80&w=600",
    name: "Globe of Earth",
    colors: ["blue", "yellow", "brown"],
    scene: "indoor",
    sentiment: "neutral",
    count: 1,
    orientation: "portrait",
    category: "object",
    tags: ["globe", "earth", "world", "map", "geography", "planet"]
  },
  {
    id: 118,
    uri: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=600",
    name: "Red Sports Shoe",
    colors: ["red", "white", "black"],
    scene: "indoor",
    sentiment: "happy",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["shoe", "sneaker", "red", "sports", "running", "footwear"]
  },
  {
    id: 119,
    uri: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=600",
    name: "Luxury Sports Car",
    colors: ["black", "silver"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["car", "luxury", "black", "expensive", "automobile", "drive"]
  },
  {
    id: 120,
    uri: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=600",
    name: "Drone Flying",
    colors: ["white", "grey", "blue"],
    scene: "outdoor",
    sentiment: "neutral",
    count: 1,
    orientation: "landscape",
    category: "object",
    tags: ["drone", "quadcopter", "flying", "aerial", "camera", "device"]
  }
];
